name: elder_care_app
description: A mobile app for tracking medicine and wellness tasks.
publish_to: 'none'

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.3
  vibration: ^1.8.3
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true